export const languages = [
  { language: 'Afrikáans', code: 'af' },
  { language: 'Albanés', code: 'sq' },
  { language: 'Árabe', code: 'ar' },
  { language: 'Azerbaiyano', code: 'az' },
  { language: 'Bengalí', code: 'bn' },
  { language: 'Búlgaro', code: 'bg' },
  { language: 'Catalán', code: 'ca' },
  { language: 'Chino (China)', code: 'zh_CN' },
  { language: 'Chino (Hong Kong)', code: 'zh_HK' },
  { language: 'Chino (Taiwán)', code: 'zh_TW' },
  { language: 'Croata', code: 'hr' },
  { language: 'Checo', code: 'cs' },
  { language: 'Danés', code: 'da' },
  { language: 'Neerlandés', code: 'nl' },
  { language: 'Inglés', code: 'en' },
  { language: 'Inglés (Reino Unido)', code: 'en_GB' },
  { language: 'Inglés (EE. UU.)', code: 'en_US' },
  { language: 'Estonio', code: 'et' },
  { language: 'Filipino', code: 'fil' },
  { language: 'Finés', code: 'fi' },
  { language: 'Francés', code: 'fr' },
  { language: 'Alemán', code: 'de' },
  { language: 'Griego', code: 'el' },
  { language: 'Guyaratí', code: 'gu' },
  { language: 'Hausa', code: 'ha' },
  { language: 'Hebreo', code: 'he' },
  { language: 'Hindi', code: 'hi' },
  { language: 'Húngaro', code: 'hu' },
  { language: 'Indonesio', code: 'id' },
  { language: 'Irlandés', code: 'ga' },
  { language: 'Italiano', code: 'it' },
  { language: 'Japonés', code: 'ja' },
  { language: 'Canarés', code: 'kn' },
  { language: 'Kazajo', code: 'kk' },
  { language: 'Coreano', code: 'ko' },
  { language: 'Lao', code: 'lo' },
  { language: 'Letón', code: 'lv' },
  { language: 'Lituano', code: 'lt' },
  { language: 'Macedonio', code: 'mk' },
  { language: 'Malayo', code: 'ms' },
  { language: 'Malayalam', code: 'ml' },
  { language: 'Maratí', code: 'mr' },
  { language: 'Noruego', code: 'nb' },
  { language: 'Persa', code: 'fa' },
  { language: 'Polaco', code: 'pl' },
  { language: 'Portugués (Brasil)', code: 'pt_BR' },
  { language: 'Portugués (Portugal)', code: 'pt_PT' },
  { language: 'Punyabí', code: 'pa' },
  { language: 'Rumano', code: 'ro' },
  { language: 'Ruso', code: 'ru' },
  { language: 'Serbio', code: 'sr' },
  { language: 'Eslovaco', code: 'sk' },
  { language: 'Esloveno', code: 'sl' },
  { language: 'Español', code: 'es' },
  { language: 'Español (Argentina)', code: 'es_AR' },
  { language: 'Español (España)', code: 'es_ES' },
  { language: 'Español (México)', code: 'es_MX' },
  { language: 'Suajili', code: 'sw' },
  { language: 'Sueco', code: 'sv' },
  { language: 'Tamil', code: 'ta' },
  { language: 'Telugu', code: 'te' },
  { language: 'Tailandés', code: 'th' },
  { language: 'Turco', code: 'tr' },
  { language: 'Ucraniano', code: 'uk' },
  { language: 'Urdu', code: 'ur' },
  { language: 'Uzbeko', code: 'uz' },
  { language: 'Vietnamita', code: 'vi' },
  { language: 'Zulu', code: 'zu' },
]

export const categories = [
  {
    name: 'Autentificación',
    value: 'AUTHENTICATION',
  },
  {
    name: 'Marketing',
    value: 'MARKETING',
  },
  {
    name: 'Utilidad',
    value: 'UTILITY',
  },
]
